x-common-env: &common-service-config
  networks:
    - comses-rag-network

services:
  models-db:
    <<: *common-service-config
    image: postgres:15-alpine
    restart: always
    container_name: models-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${MODELS_DB_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - ${MODELS_DB_DATA_PATH}:/var/lib/postgresql/data

  qdrant:
      <<: *common-service-config
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      environment:
        - QDRANT__SERVICE__HTTP_PORT=${QDRANT_PORT}
        - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
        - QDRANT__TELEMETRY_DISABLED=${QDRANT_DISABLE_TELEMETRY}
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      configs:
        - source: qdrant_config
          target: /qdrant/config/production.yaml
      volumes:
        - ./local_data/qdrant_data:/qdrant/storage
  minio:
    <<: *common-service-config
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
    restart: unless-stopped
    volumes:
      - ./local_data/minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: minio server /data

networks:
  temporal-network:
    external: true

  comses-rag-network:
    name: comses-rag-network
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO