x-app-env: &app-env
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  PYTHONUNBUFFERED: 1

x-temporal-env: &temporal-env
  TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS}

x-comses-env: &comses-env
  COMSES_URL: ${COMSES_URL}

x-ollama-env: &ollama-env
  OLLAMA_URL: ${OLLAMA_URL}

services:
  spam-check-worker:
    profiles:
      - worker
    image: ghcr.io/asuworks/comses.rag/spam-check-worker:v0.1
    build:
      context: .
      dockerfile: ./spam_check/workers/spam_check_worker/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env
    command: [ "python", "/app/spam_check/workers/spam_check_worker/run.py" ]
    environment:
      <<: [ *app-env, *temporal-env, *comses-env, *ollama-env ]
    volumes:
      - ./spam_check:/app/spam_check
      - ./shared:/app/shared
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - temporal-network
      - spam-check-network

  ollama-worker:
    profiles:
      - worker
    image: ghcr.io/asuworks/comses.rag/ollama-worker:v0.1
    build:
      context: .
      dockerfile: ./shared/workers/ollama_worker/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env
    command: [ "python", "/app/shared/workers/ollama_worker/run.py" ]
    environment:
      <<: [ *app-env, *temporal-env, *comses-env, *ollama-env ]
    volumes:
      - ./spam_check:/app/spam_check
      - ./shared:/app/shared
    networks:
      - temporal-network
      - ollama-docker
networks:
  temporal-network:
    external: true
  ollama-docker:
    external: true
  spam-check-network:
    name: spam-check-network
    driver: bridge
